-- MySQL Script generated by MySQL Workbench
-- Sat Aug 31 21:31:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jurusan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jurusan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kode_jurusan` VARCHAR(45) NULL,
  `nama_jurusan` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mata_kuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mata_kuliah` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kode_mata_kuliah` VARCHAR(45) NULL,
  `maat_kuliah` VARCHAR(45) NULL,
  `jurusan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mata_kuliah_jurusan_idx` (`jurusan_id` ASC) VISIBLE,
  CONSTRAINT `fk_mata_kuliah_jurusan`
    FOREIGN KEY (`jurusan_id`)
    REFERENCES `mydb`.`jurusan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dosen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dosen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kode_dosen` VARCHAR(45) NULL,
  `nama` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mata_kuliah_has_dosen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mata_kuliah_has_dosen` (
  `mata_kuliah_id` INT NOT NULL,
  `dosen_id` INT NOT NULL,
  PRIMARY KEY (`mata_kuliah_id`, `dosen_id`),
  INDEX `fk_mata_kuliah_has_dosen_dosen1_idx` (`dosen_id` ASC) VISIBLE,
  INDEX `fk_mata_kuliah_has_dosen_mata_kuliah1_idx` (`mata_kuliah_id` ASC) VISIBLE,
  CONSTRAINT `fk_mata_kuliah_has_dosen_mata_kuliah1`
    FOREIGN KEY (`mata_kuliah_id`)
    REFERENCES `mydb`.`mata_kuliah` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mata_kuliah_has_dosen_dosen1`
    FOREIGN KEY (`dosen_id`)
    REFERENCES `mydb`.`dosen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mahasiswa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kode_mahasiswa` VARCHAR(45) NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jurusan_has_mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jurusan_has_mahasiswa` (
  `jurusan_id` INT NOT NULL,
  `mahasiswa_id` INT NOT NULL,
  PRIMARY KEY (`jurusan_id`, `mahasiswa_id`),
  INDEX `fk_jurusan_has_mahasiswa_mahasiswa1_idx` (`mahasiswa_id` ASC) VISIBLE,
  INDEX `fk_jurusan_has_mahasiswa_jurusan1_idx` (`jurusan_id` ASC) VISIBLE,
  CONSTRAINT `fk_jurusan_has_mahasiswa_jurusan1`
    FOREIGN KEY (`jurusan_id`)
    REFERENCES `mydb`.`jurusan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jurusan_has_mahasiswa_mahasiswa1`
    FOREIGN KEY (`mahasiswa_id`)
    REFERENCES `mydb`.`mahasiswa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mahasiswa_has_mata_kuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mahasiswa_has_mata_kuliah` (
  `mahasiswa_id` INT NOT NULL,
  `mata_kuliah_id` INT NOT NULL,
  PRIMARY KEY (`mahasiswa_id`, `mata_kuliah_id`),
  INDEX `fk_mahasiswa_has_mata_kuliah_mata_kuliah1_idx` (`mata_kuliah_id` ASC) VISIBLE,
  INDEX `fk_mahasiswa_has_mata_kuliah_mahasiswa1_idx` (`mahasiswa_id` ASC) VISIBLE,
  CONSTRAINT `fk_mahasiswa_has_mata_kuliah_mahasiswa1`
    FOREIGN KEY (`mahasiswa_id`)
    REFERENCES `mydb`.`mahasiswa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mahasiswa_has_mata_kuliah_mata_kuliah1`
    FOREIGN KEY (`mata_kuliah_id`)
    REFERENCES `mydb`.`mata_kuliah` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
